-- =============================================================================
-- P1 Schema Migration: Indexes, Constraints, and FK Cascade Behaviors
-- =============================================================================
-- Run this migration ONCE against the production database AFTER deploying the
-- P1 code changes (shared/schema.ts).  It is safe to re-run — every statement
-- is guarded with IF NOT EXISTS or DROP IF EXISTS / CREATE IF NOT EXISTS idioms.
--
-- Prerequisites:
--   1. P0 fixes are deployed and the database is running.
--   2. Take a snapshot/backup before running.
--   3. Run as the database owner or a role with DDL privileges.
--
-- IMPORTANT: The CONCURRENTLY variants for index creation do NOT run inside a
-- transaction, so we execute them outside a transaction block.  All other DDL
-- that modifies constraints runs inside a transaction for atomicity.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- PART 1: New indexes (CONCURRENTLY — no locking, can run on live production)
-- ---------------------------------------------------------------------------

-- SCHEMA-01: Composite query indexes on performance_data
-- (created CONCURRENTLY so they don't block reads/writes)

CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_perf_school_year_ind
  ON performance_data (school_id, academic_year, indicator_id);

CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_perf_district_year_ind
  ON performance_data (district_id, academic_year, indicator_id);

CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_perf_county_year_ind
  ON performance_data (county_id, academic_year, indicator_id);

CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_perf_ind_group_year
  ON performance_data (indicator_id, student_group_id, academic_year);

-- SCHEMA-03: Expression-based dedupe unique index.
-- Uses COALESCE(x, 0) so NULL values at the same reporting level compare equal.
-- (0 is never a valid serial id so it is safe as a sentinel.)
-- Drop the simple drizzle-managed unique index first (if present from drizzle push),
-- then create the richer expression-based one.
DROP INDEX CONCURRENTLY IF EXISTS idx_perf_dedupe;

CREATE UNIQUE INDEX CONCURRENTLY IF NOT EXISTS idx_perf_dedupe
  ON performance_data (
    COALESCE(school_id,    0),
    COALESCE(district_id,  0),
    COALESCE(county_id,    0),
    indicator_id,
    student_group_id,
    academic_year
  );

-- SCHEMA-05: Partial unique index on users.email (non-null only).
-- PostgreSQL's standard UNIQUE constraint already allows multiple NULLs, so
-- this partial index is semantically equivalent but makes intent explicit.
-- Drop the old inline unique constraint first (name is auto-generated by drizzle
-- as "users_email_unique").
ALTER TABLE users DROP CONSTRAINT IF EXISTS users_email_unique;

CREATE UNIQUE INDEX CONCURRENTLY IF NOT EXISTS idx_users_email_unique
  ON users (email)
  WHERE email IS NOT NULL;

-- ---------------------------------------------------------------------------
-- PART 2: FK constraint changes and CHECK constraint (inside a transaction)
-- ---------------------------------------------------------------------------

BEGIN;

-- SCHEMA-04: districts → counties — CASCADE on delete.
ALTER TABLE districts
  DROP CONSTRAINT IF EXISTS districts_county_id_counties_id_fk;
ALTER TABLE districts
  ADD CONSTRAINT districts_county_id_counties_id_fk
  FOREIGN KEY (county_id) REFERENCES counties (id) ON DELETE CASCADE;

-- SCHEMA-04: schools → districts — CASCADE on delete.
ALTER TABLE schools
  DROP CONSTRAINT IF EXISTS schools_district_id_districts_id_fk;
ALTER TABLE schools
  ADD CONSTRAINT schools_district_id_districts_id_fk
  FOREIGN KEY (district_id) REFERENCES districts (id) ON DELETE CASCADE;

-- SCHEMA-04: schools → counties — CASCADE on delete.
ALTER TABLE schools
  DROP CONSTRAINT IF EXISTS schools_county_id_counties_id_fk;
ALTER TABLE schools
  ADD CONSTRAINT schools_county_id_counties_id_fk
  FOREIGN KEY (county_id) REFERENCES counties (id) ON DELETE CASCADE;

-- SCHEMA-04: performance_data → schools — CASCADE on delete.
ALTER TABLE performance_data
  DROP CONSTRAINT IF EXISTS performance_data_school_id_schools_id_fk;
ALTER TABLE performance_data
  ADD CONSTRAINT performance_data_school_id_schools_id_fk
  FOREIGN KEY (school_id) REFERENCES schools (id) ON DELETE CASCADE;

-- SCHEMA-04: performance_data → districts — CASCADE on delete.
ALTER TABLE performance_data
  DROP CONSTRAINT IF EXISTS performance_data_district_id_districts_id_fk;
ALTER TABLE performance_data
  ADD CONSTRAINT performance_data_district_id_districts_id_fk
  FOREIGN KEY (district_id) REFERENCES districts (id) ON DELETE CASCADE;

-- SCHEMA-04: performance_data → counties — CASCADE on delete.
ALTER TABLE performance_data
  DROP CONSTRAINT IF EXISTS performance_data_county_id_counties_id_fk;
ALTER TABLE performance_data
  ADD CONSTRAINT performance_data_county_id_counties_id_fk
  FOREIGN KEY (county_id) REFERENCES counties (id) ON DELETE CASCADE;

-- SCHEMA-04: performance_data → indicators — RESTRICT (never silently delete referenced data).
ALTER TABLE performance_data
  DROP CONSTRAINT IF EXISTS performance_data_indicator_id_indicators_id_fk;
ALTER TABLE performance_data
  ADD CONSTRAINT performance_data_indicator_id_indicators_id_fk
  FOREIGN KEY (indicator_id) REFERENCES indicators (id) ON DELETE RESTRICT;

-- SCHEMA-04: performance_data → student_groups — RESTRICT.
ALTER TABLE performance_data
  DROP CONSTRAINT IF EXISTS performance_data_student_group_id_student_groups_id_fk;
ALTER TABLE performance_data
  ADD CONSTRAINT performance_data_student_group_id_student_groups_id_fk
  FOREIGN KEY (student_group_id) REFERENCES student_groups (id) ON DELETE RESTRICT;

-- SCHEMA-04: api_usage_logs → api_keys — CASCADE on delete.
ALTER TABLE api_usage_logs
  DROP CONSTRAINT IF EXISTS api_usage_logs_api_key_id_api_keys_id_fk;
ALTER TABLE api_usage_logs
  ADD CONSTRAINT api_usage_logs_api_key_id_api_keys_id_fk
  FOREIGN KEY (api_key_id) REFERENCES api_keys (id) ON DELETE CASCADE;

-- SCHEMA-02: CHECK constraint — valid reporting-level combinations.
-- Existing rows must conform before adding the constraint.
-- If this fails, inspect: SELECT * FROM performance_data WHERE NOT (
--   (school_id IS NULL AND district_id IS NULL AND county_id IS NULL) OR
--   (school_id IS NULL AND district_id IS NULL AND county_id IS NOT NULL) OR
--   (school_id IS NULL AND district_id IS NOT NULL AND county_id IS NOT NULL) OR
--   (school_id IS NOT NULL AND district_id IS NOT NULL AND county_id IS NOT NULL)
-- );
ALTER TABLE performance_data
  DROP CONSTRAINT IF EXISTS chk_perf_level_consistency;
ALTER TABLE performance_data
  ADD CONSTRAINT chk_perf_level_consistency CHECK (
    (school_id IS NULL     AND district_id IS NULL     AND county_id IS NULL)     OR
    (school_id IS NULL     AND district_id IS NULL     AND county_id IS NOT NULL) OR
    (school_id IS NULL     AND district_id IS NOT NULL AND county_id IS NOT NULL) OR
    (school_id IS NOT NULL AND district_id IS NOT NULL AND county_id IS NOT NULL)
  );

COMMIT;

-- ---------------------------------------------------------------------------
-- PART 3: Verification queries (run these manually after migration)
-- ---------------------------------------------------------------------------
-- Check indexes are present:
--   SELECT indexname, indexdef FROM pg_indexes WHERE tablename = 'performance_data' ORDER BY 1;
--   SELECT indexname, indexdef FROM pg_indexes WHERE tablename = 'users' ORDER BY 1;
--
-- Check FK constraints:
--   SELECT conname, contype, confdeltype FROM pg_constraint
--   WHERE conrelid = 'performance_data'::regclass ORDER BY 1;
--
-- Check CHECK constraint:
--   SELECT conname FROM pg_constraint
--   WHERE conrelid = 'performance_data'::regclass AND contype = 'c';
--
-- Expected row counts after successful re-ingest:
--   SELECT 'counties' AS tbl, count(*) FROM counties     -- ~58
--   UNION ALL
--   SELECT 'districts',       count(*) FROM districts    -- ~1,000
--   UNION ALL
--   SELECT 'schools',         count(*) FROM schools      -- ~10,000
--   UNION ALL
--   SELECT 'performance_data',count(*) FROM performance_data; -- hundreds of thousands
